language: ruby

rvm:
  - 2.1.2

bundler_args: --without development
cache: bundler

before_script:
  - npm install
  - npm install -g bower
  - bower install
  - gulp compile

script:
  - bundle exec rspec spec
