language: ruby

rvm:
  - 2.1.2

branches:
  only: 
    - master
    - production

before_script:
  - npm cache clean
  - npm install
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - gulp compile

script:
  - bundle exec rspec spec
